"""Emit catalog outputs: JSONL, Markdown, HTML."""
from __future__ import annotations

import html as _html
import json
from datetime import datetime
from pathlib import Path


BUCKET_ORDER = ["active", "archival", "reference", "deprecated", "runtime"]
BUCKET_EMOJI = {"active": "🟢", "archival": "🟡", "reference": "📦", "deprecated": "⚰️", "runtime": "🔧"}
BUCKET_LABEL = {
    "active":     "Active",
    "archival":   "Archival",
    "reference":  "Reference",
    "deprecated": "Deprecated",
    "runtime":    "Runtime",
}


def write_jsonl(records: list[dict], catalog_dir: Path, description_budget: int) -> dict:
    catalog_dir.mkdir(parents=True, exist_ok=True)
    counts = {"total": len(records)}

    def _dump(path: Path, recs: list[dict]) -> None:
        with path.open("w", encoding="utf-8") as f:
            for r in recs:
                slim = dict(r)
                slim["sub_skills"] = None
                f.write(json.dumps(slim, ensure_ascii=False, separators=(",", ":")) + "\n")

    _dump(catalog_dir / "catalog.jsonl", records)
    active = [r for r in records if r.get("status") == "active"]
    inactive = [r for r in records if r.get("status") != "active"]
    _dump(catalog_dir / "catalog_active.jsonl", active)
    _dump(catalog_dir / "catalog_inactive.jsonl", inactive)
    counts["active"] = len(active)
    counts["inactive"] = len(inactive)

    # Budget check: Claude Code silently truncates description text past a limit.
    total_desc = sum(len(r.get("description", "")) for r in active)
    counts["description_chars"] = total_desc
    counts["description_over_budget"] = max(0, total_desc - description_budget)
    return counts


def write_md(records: list[dict], catalog_dir: Path, machine: str) -> Path:
    by_status: dict = {}
    for r in records:
        by_status.setdefault(r["status"], []).append(r)

    today = datetime.now().strftime("%Y-%m-%d %H:%M")
    L: list[str] = []
    L += [f"# Skill Catalog — {today}", ""]
    L += [f"_Generated by `skillctl rebuild` · machine: `{machine}` · {len(records)} skills total_", ""]
    L += ["---", "", "## Inventory", ""]
    for bucket in BUCKET_ORDER:
        recs = by_status.get(bucket, [])
        if not recs:
            continue
        origin_counts: dict = {}
        for r in recs:
            origin_counts[r["origin"]] = origin_counts.get(r["origin"], 0) + 1
        origin_str = ", ".join(f"{o}={c}" for o, c in sorted(origin_counts.items()))
        L.append(f"- {BUCKET_EMOJI[bucket]} **{BUCKET_LABEL[bucket]}**: **{len(recs)}** ({origin_str})")
    L.append("")

    active_recs = by_status.get("active", [])
    used = [r for r in active_recs if r.get("usage_30d", 0) > 0]
    if used:
        total = max(len(active_recs), 1)
        L += [
            "## Usage (last 30 days)", "",
            f"- Invoked: **{len(used)}** of {len(active_recs)} ({100 * len(used) // total}%)",
            f"- Never invoked: **{len(active_recs) - len(used)}**", "",
            "**Top 10:**", "",
        ]
        for r in sorted(used, key=lambda x: -x["usage_30d"])[:10]:
            last = (r.get("last_used") or "")[:10]
            L.append(f"- `{r['name']}` × **{r['usage_30d']}**  ·  last: {last}")
        L.append("")

    L += ["---", ""]

    for bucket in BUCKET_ORDER:
        recs = by_status.get(bucket, [])
        if not recs:
            continue
        L += [f"## {BUCKET_EMOJI[bucket]} {BUCKET_LABEL[bucket]} ({len(recs)})", ""]
        for r in sorted(recs, key=lambda x: (x["origin"], x["name"])):
            tags = [f"`{r['origin']}`"]
            if r.get("goal"):
                tags.append(f"`{r['goal']}`")
            if r.get("sub_skill_count"):
                tags.append(f"{r['sub_skill_count']} sub-skills")
            L.append(f"### {r['name']}  ·  {' · '.join(tags)}")
            desc = (r.get("description") or "").split("\n")[0][:300]
            if desc:
                L.append(desc)
            if r.get("usage_30d", 0) > 0:
                last = (r.get("last_used") or "")[:10]
                L.append(f"- 🔥 30d: **{r['usage_30d']}**  ·  last: {last}")
            if r.get("triggers"):
                L.append(f"- triggers: {', '.join(r['triggers'][:8])}")
            L.append(f"- path: `{r['source_path']}`")
            L.append("")

    p = catalog_dir / "catalog.md"
    p.write_text("\n".join(L), encoding="utf-8")
    return p


def write_html(records: list[dict], catalog_dir: Path, machine: str) -> Path:
    by_status: dict = {}
    for r in records:
        by_status.setdefault(r["status"], []).append(r)
    active = by_status.get("active", [])
    used = [r for r in active if r.get("usage_30d", 0) > 0]
    usage_pct = (100 * len(used) // max(len(active), 1)) if active else 0

    status_labels = json.dumps([BUCKET_LABEL.get(s, s) for s in BUCKET_ORDER if s in by_status])
    status_data = json.dumps([len(by_status.get(s, [])) for s in BUCKET_ORDER if s in by_status])
    origin_counts: dict = {}
    for r in active:
        origin_counts[r["origin"]] = origin_counts.get(r["origin"], 0) + 1
    origin_labels = json.dumps(sorted(origin_counts.keys()))
    origin_data = json.dumps([origin_counts[k] for k in sorted(origin_counts.keys())])
    top_used = sorted(used, key=lambda x: -x.get("usage_30d", 0))[:10]
    usage_labels = json.dumps([r["name"] for r in top_used])
    usage_vals = json.dumps([r.get("usage_30d", 0) for r in top_used])

    rows = []
    for r in sorted(active, key=lambda x: (-x.get("usage_30d", 0), x["name"])):
        name = _html.escape(r["name"])
        origin = r.get("origin", "")
        goal = r.get("goal") or ""
        u30 = r.get("usage_30d", 0)
        triggers = ", ".join(r.get("triggers", [])[:5])
        tag_cls = f"tag-{origin}" if origin in ("self", "community", "vendor", "deprecated") else ""
        rows.append(
            f'<tr><td><b>{name}</b></td><td><span class="{tag_cls}">{origin}</span></td>'
            f'<td>{goal}</td><td>{"🔥 " + str(u30) if u30 else "—"}</td>'
            f'<td>{_html.escape(triggers)}</td></tr>'
        )
    skill_rows = "\n".join(rows)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    total = len(records)
    usage_chart_html = '<canvas id="usageChart" height="200"></canvas>' if top_used else '<p style="color:#999">No usage data yet</p>'
    usage_chart_js = (
        f'new Chart(document.getElementById("usageChart"),{{type:"bar",'
        f'data:{{labels:{usage_labels},datasets:[{{label:"30d calls",data:{usage_vals},backgroundColor:"#ef5350"}}]}},'
        f'options:{{responsive:true,indexAxis:"y",plugins:{{legend:{{display:false}}}}}}}});'
    ) if top_used else ""

    html_doc = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>skillctl — Catalog Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<style>
*{{box-sizing:border-box}}
body{{font-family:-apple-system,system-ui,sans-serif;max-width:1200px;margin:0 auto;padding:20px;background:#f8f9fa;color:#1a1a2e}}
h1{{font-size:2em;font-weight:800;margin-bottom:4px}}
.subtitle{{color:#666;margin-bottom:24px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin-bottom:24px}}
.card{{background:#fff;border-radius:12px;padding:20px;box-shadow:0 1px 4px rgba(0,0,0,.06)}}
.stat-num{{font-size:2.8em;font-weight:800;line-height:1.1}}
.stat-label{{font-size:.9em;color:#888;margin-top:4px}}
.chart-grid{{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px}}
@media(max-width:768px){{.chart-grid{{grid-template-columns:1fr}}}}
input#search{{width:100%;padding:10px 14px;font-size:1em;border:1px solid #ddd;border-radius:8px;margin-bottom:12px;outline:none}}
table{{width:100%;border-collapse:collapse;font-size:.9em}}
th{{text-align:left;padding:8px 10px;border-bottom:2px solid #e0e0e0;font-weight:600}}
td{{padding:8px 10px;border-bottom:1px solid #f0f0f0}}
tr:hover{{background:#f8f9fa}}
.tag-self{{background:#e8f5e9;color:#2e7d32;padding:2px 8px;border-radius:4px;font-size:.85em}}
.tag-community{{background:#e3f2fd;color:#1565c0;padding:2px 8px;border-radius:4px;font-size:.85em}}
.tag-vendor{{background:#fff3e0;color:#e65100;padding:2px 8px;border-radius:4px;font-size:.85em}}
.tag-deprecated{{background:#f5f5f5;color:#999;padding:2px 8px;border-radius:4px;font-size:.85em}}
</style></head><body>
<h1>skillctl Dashboard</h1>
<p class="subtitle">machine: <b>{machine}</b> · {ts} · <b>{total}</b> skills</p>
<div class="grid">
  <div class="card"><div class="stat-num" style="color:#4caf50">{len(active)}</div><div class="stat-label">Active</div></div>
  <div class="card"><div class="stat-num" style="color:#ef5350">{usage_pct}%</div><div class="stat-label">30-day usage ({len(used)}/{len(active)})</div></div>
  <div class="card"><div class="stat-num" style="color:#ff9800">{len(by_status.get("archival", []))}</div><div class="stat-label">Archival</div></div>
  <div class="card"><div class="stat-num">{total}</div><div class="stat-label">Total</div></div>
</div>
<div class="chart-grid">
  <div class="card"><h3>Status</h3><canvas id="statusChart"></canvas></div>
  <div class="card"><h3>Origin (active)</h3><canvas id="originChart"></canvas></div>
</div>
<div class="card" style="margin-bottom:24px"><h3>Top Usage (30d)</h3>{usage_chart_html}</div>
<div class="card">
  <h3>Active Skills ({len(active)})</h3>
  <input id="search" type="text" placeholder="Search by name, trigger, goal...">
  <table id="skillTable"><thead><tr><th>Name</th><th>Origin</th><th>Goal</th><th>30d</th><th>Triggers</th></tr></thead>
  <tbody>{skill_rows}</tbody></table>
</div>
<script>
new Chart(document.getElementById("statusChart"),{{type:"doughnut",data:{{labels:{status_labels},datasets:[{{data:{status_data},backgroundColor:["#4caf50","#ffc107","#2196f3","#9e9e9e","#795548"]}}]}},options:{{responsive:true,plugins:{{legend:{{position:"bottom"}}}}}}}});
new Chart(document.getElementById("originChart"),{{type:"doughnut",data:{{labels:{origin_labels},datasets:[{{data:{origin_data},backgroundColor:["#43a047","#1e88e5","#fb8c00","#757575"]}}]}},options:{{responsive:true,plugins:{{legend:{{position:"bottom"}}}}}}}});
{usage_chart_js}
document.getElementById("search").addEventListener("input",function(){{var q=this.value.toLowerCase();document.querySelectorAll("#skillTable tbody tr").forEach(function(r){{r.style.display=r.textContent.toLowerCase().includes(q)?"":"none"}});}});
</script>
</body></html>"""
    p = catalog_dir / "catalog.html"
    p.write_text(html_doc, encoding="utf-8")
    return p
